
import HB_LifeCycle

a = HB_LifeCycle.Adult_male("light brown","meadows", 21, "Tamir" )
a.Identification()
a.speak()
a.flight()
a.food()
a.function()
a.mating()
a.bomb()
a.suicide()
a.run()
a.red_bee()
q = HB_LifeCycle.Queen("light brown"," meadows", 16,"Keren")
q.Identification()
q.speak()
q.waggeling()
q.flight()
q.food()
q.function()
q.flight()
q.sting()
q.attack()
q.run()
p = HB_LifeCycle.Pupa("whitish", "inside an honeycomb", 8 ,"Eran")
p.Identification()
p.flight()
l = HB_LifeCycle.Larva("whitish", "inside an honeycomb", 4,"Kobi")
l.Identification()
l.food()
l.feed()
l.eating()
e = HB_LifeCycle.Egg("whitish", "inside an honeycomb", 1,"David")
e.Identification()
